// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuZJvjS9O4GW1fE2pMs_K_kkQnxprvPvY',
    appId: '1:1076434989317:web:6311d375f1082697d7876c',
    messagingSenderId: '1076434989317',
    projectId: 'learnasff',
    authDomain: 'learnasff.firebaseapp.com',
    storageBucket: 'learnasff.appspot.com',
    measurementId: 'G-LJ8WH4E5QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQE0Ldu7eOA6Q1HLqhZbTnBGVCwPUNND8',
    appId: '1:1076434989317:android:db996e628cb1d5d7d7876c',
    messagingSenderId: '1076434989317',
    projectId: 'learnasff',
    storageBucket: 'learnasff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDikhy1jHEnzCpkxKKrsFAhW53-Jxv62Ng',
    appId: '1:1076434989317:ios:651702c6fb72dc5ad7876c',
    messagingSenderId: '1076434989317',
    projectId: 'learnasff',
    storageBucket: 'learnasff.appspot.com',
    iosClientId: '1076434989317-8ci2vhb84ijbp59jlmrrqgip4p2cd0c8.apps.googleusercontent.com',
    iosBundleId: 'com.example.denme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDikhy1jHEnzCpkxKKrsFAhW53-Jxv62Ng',
    appId: '1:1076434989317:ios:651702c6fb72dc5ad7876c',
    messagingSenderId: '1076434989317',
    projectId: 'learnasff',
    storageBucket: 'learnasff.appspot.com',
    iosClientId: '1076434989317-8ci2vhb84ijbp59jlmrrqgip4p2cd0c8.apps.googleusercontent.com',
    iosBundleId: 'com.example.denme',
  );
}
